site_name: Metabase SDK for Go
site_url: !ENV [SITE_URL, '']
docs_dir: docs
use_directory_urls: false

repo_url: https://github.com/bnjns/metabase-sdk-go
repo_name: bnjns/metabase-sdk-go

theme:
  name: material
  features:
    - navigation.expand
    - navigation.instant

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction: index.md
  - Authentication: authentication.md
  - Services:
      - Database: services/database.md
      - Permissions: services/permissions.md
      - User: services/user.md
  - Reference Documentation: https://pkg.go.dev/github.com/bnjns/metabase-sdk-go
