title: Metabase SDK for Go
email: ben@bnjns.uk
description: An SDK for interacting with the Metabase API for the Go programming language.
baseurl: ""
url: ""
github_username:  bnjns

theme: just-the-docs
plugins:
  - just-the-docs
  - kramdown
  - jekyll-relative-links

nav_external_links:
  - title: Reference documentation
    url: https://pkg.go.dev/github.com/bnjns/metabase-sdk-go/

callouts:
  info:
    title: Info
    color: blue
  warning:
    title: Warning
    color: yellow

collections:
  services:
    output: true

just_the_docs:
  collections:
    services:
      name: Services
      nav_fold: false

defaults:
  - values:
      layout: default
